# Generated by Django 3.2.4 on 2021-06-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user_name', models.CharField(db_column='user_name', max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_column='region', max_length=255, null=True)),
                ('graduation_school', models.CharField(blank=True, db_column='graduation_school', max_length=255, null=True)),
                ('major', models.CharField(blank=True, db_column='major', max_length=255, null=True)),
                ('transfer', models.CharField(blank=True, db_column='transfer', max_length=255, null=True)),
                ('remarks', models.TextField(db_column='remarks')),
                ('test_number', models.CharField(blank=True, db_column='test_number', max_length=255, null=True)),
            ],
            options={
                'db_table': 'applicant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'applicant_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_time', models.CharField(blank=True, max_length=255, null=True)),
                ('course_place', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type', models.CharField(blank=True, max_length=255, null=True)),
                ('course_teacher', models.CharField(blank=True, max_length=255, null=True)),
                ('course_credit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'course_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=255)),
                ('course_rank', models.CharField(max_length=255)),
                ('course_length', models.CharField(max_length=255)),
                ('course_choice', models.CharField(max_length=255)),
                ('course_credit', models.IntegerField()),
            ],
            options={
                'db_table': 'course_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseScore',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=255)),
                ('course_length', models.CharField(max_length=255)),
                ('course_credit', models.CharField(max_length=255)),
                ('course_score', models.CharField(max_length=255)),
                ('course_ranking', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_time', models.CharField(max_length=255)),
                ('course_place', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=255)),
                ('course_credit', models.IntegerField()),
                ('course_teacher', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraduateEdu',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('further_school', models.CharField(blank=True, max_length=255, null=True)),
                ('further_major', models.CharField(blank=True, max_length=255, null=True)),
                ('further_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('further_full_part_time', models.CharField(blank=True, db_collation='utf8_bin', max_length=1, null=True)),
                ('further_start_time', models.DateField(blank=True, null=True)),
                ('further_graduate_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graduate_edu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraduateJob',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('graduate_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_job_position', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_job_start_time', models.DateField(blank=True, null=True)),
                ('graduate_job_end_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graduate_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraduateReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_depart_nation', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_depart_province', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_depart_city', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_return_date', models.DateField(blank=True, null=True)),
                ('graduate_return_time', models.TimeField(blank=True, null=True)),
                ('graduate_return_campus', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_return_gate', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'graduate_return',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBasic',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
                ('entrance_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.CharField(blank=True, max_length=255, null=True)),
                ('electricity_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('dorm', models.CharField(blank=True, max_length=255, null=True)),
                ('educate_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('score_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('gpa', models.CharField(blank=True, db_column='GPA', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('work_place', models.CharField(blank=True, max_length=255, null=True)),
                ('home', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(db_collation='utf8mb4_cs_0900_ai_ci', max_length=255)),
            ],
            options={
                'db_table': 'student_basic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('course_score', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'student_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=20, null=True)),
                ('identity', models.CharField(blank=True, max_length=30, null=True)),
                ('id_number', models.CharField(blank=True, max_length=18, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('true_name', models.CharField(blank=True, db_collation='utf8mb4_cs_0900_ai_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
