# Generated by Django 3.2 on 2021-06-20 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='user_name', max_length=30)),
                ('password', models.CharField(db_column='password', max_length=30)),
                ('create_time', models.DateTimeField(db_column='create_time', default=datetime.date(2021, 6, 20))),
                ('identity', models.CharField(db_column='identity', max_length=20)),
                ('id_number', models.CharField(db_column='id_number', max_length=18)),
                ('age', models.IntegerField(db_column='age')),
                ('gender', models.BinaryField(db_column='gender')),
                ('email', models.CharField(db_column='email', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
