# Generated by Django 3.2.4 on 2021-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210626_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user_name', models.CharField(db_column='user_name', max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_column='region', max_length=255, null=True)),
                ('graduation_school', models.CharField(blank=True, db_column='graduation_school', max_length=255, null=True)),
                ('major', models.CharField(blank=True, db_column='major', max_length=255, null=True)),
                ('transfer', models.CharField(blank=True, db_column='transfer', max_length=255, null=True)),
                ('remarks', models.TextField(db_column='remarks')),
                ('test_number', models.CharField(blank=True, db_column='test_number', max_length=255, null=True)),
            ],
            options={
                'db_table': 'applicant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'applicant_test',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
